---
site_name: Ansible project template
site_url: https://ansible.readthedocs.io/PROJECTNAME
repo_url: https://github.com/ansible/PROJECTNAME
edit_uri: blob/main/docs/
docs_dir: docs
strict: true

theme:
  name: "ansible"

nav:
  - index.md
  - getting_started_user.md
  - installing.md
  - User Guide:
    - user_guide/how_to_xxx.md
  - References:
    - references/cli.md
    - references/porting_guide.md
    - references/roadmap.md


#see mkdocs for other optional extensions
