---
site_name: Ansible project template
site_url: https://ansible.readthedocs.io/PROJECTNAME
repo_url: https://github.com/ansible-community/project-template
edit_uri: blob/main/docs/
docs_dir: docs
strict: true

theme:
  name: 'ansible'

nav:
  - Home: 'index.md'
  - 'community_guide.md'
    - 'community_guide.md#code-of-conduct'
    - 'community_guide.md#communication'
      - 'community_guide.md#asynchronous-channels'
      - 'community_guide.md#real-time-channels'
  - 'user_guide.md'
    - 'user_guide.md#getting-started'
    - 'user_guide.md#installation'
    - 'user_guide.md#next-section'
  - 'contributor_guide.md'
    - 'contributor_guide.md#project-place-in-ansible-ecosystem'
    - 'contributor_guide.md#non-code-contribution'
      - 'contributor_guide.md#ask-and-answer-questions'
      - 'contributor_guide.md#contributing-to-documentation'
      - 'contributor_guide.md#how-to-open-an-issue'
    - 'contributor_guide.md#code-contributions'
      - 'contributor_guide.md#project-architectur'
      - 'contributor_guide.md#getting-started'
      - 'contributor_guide.md#testing'
      - 'contributor_guide.md#reviewing-open-issues-and-pull-requests'
  - 'maintainer_guide.md'
    - 'maintainer_guide.md#how-to-become-a-maintaine'
    - 'maintainer_guide.md#maintainer-responsibilities'
    - 'maintainer_guide.md#releasing'
      - 'maintainer_guide.md#versioning-and-deprecation'
      - 'maintainer_guide.md#conducting-releases'
    - 'maintainer_guide.md#stepping-down-as-a-maintaine'
  - References:
    - 'references/cli.md'

# See https://www.mkdocs.org/user-guide/configuration/ for more information
